# Generated by Django 5.2.3 on 2025-07-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('image', models.ImageField(upload_to='post_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
