# Generated by Django 5.2.3 on 2025-07-09 06:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='This is the default content for the post.', verbose_name='Content'),
        ),
    ]
